name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  create-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create EC2 instance
        run: |
          aws ec2 run-instances --image-id ami-07d9b9ddc6cd8dd30 --count 2 --instance-type t2.micro --key-name ansible1 --security-group-ids sg-0185741867f404fbc --subnet-id subnet-0784c1155f565373e --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyInstance}]'
